database_url: "${DATABASE_URL}"

data_sources:
  - name: "weather_gov"
    base_url: "https://api.weather.gov"
    user_agent: "weather-risk (luisangel.esparza2022@gmail.com)"

  - name: "openweather"
    base_url: "https://api.openweathermap.org/data/3.0/onecall?units=imperial"
    api_key: "${OPENWEATHER_API_KEY}"

log_path: "log/ingestion.log"
retry:
  max: 3
  backoff: 2

